addableTables={}
addableTables["AffResource"]={
    "Id" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "Notes" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "ProgramIds" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "ResourceHREF" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "ResourceHTML" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "ResourceOrder" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "ResourceType" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Title" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    }
addableTables["Affiliate"]={
    "AffCode" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "AffName" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "ContactId" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "DefCommissionType" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    "LeadAmt" : ["Double", [ "Edit", "Delete", "Add", "Read" ] ],
    "LeadCookieFor" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    "LeadPercent" : ["Double", [ "Edit", "Delete", "Add", "Read" ] ],
    "NotifyLead" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    "NotifySale" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    "ParentId" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "Password" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "PayoutType" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    "SaleAmt" : ["Double", [ "Edit", "Delete", "Add", "Read" ] ],
    "SalePercent" : ["Double", [ "Edit", "Delete", "Add", "Read" ] ],
    "Status" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    }
addableTables["CProgram"]={
    "Active" : ["Boolean", [ "Edit", "Add", "Read" ] ],
    "BillingType" : ["String", [ "Edit", "Add", "Read" ] ],
    "DefaultCycle" : ["String", [ "Edit", "Add", "Read" ] ],
    "DefaultFrequency" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "DefaultPrice" : ["Double", [ "Edit", "Add", "Read" ] ],
    "Description" : ["String", [ "Edit", "Add", "Read" ] ],
    "Family" : ["String", [ "Edit", "Add", "Read" ] ],
    "HideInStore" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "LargeImage" : ["Blob", [ "Edit", "Add", "Read" ] ],
    "ProductId" : ["Id", [ "Edit", "Add", "Read" ] ],
    "ProgramName" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShortDescription" : ["String", [ "Edit", "Add", "Read" ] ],
    "Sku" : ["String", [ "Edit", "Add", "Read" ] ],
    "Status" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "Taxable" : ["Integer", [ "Edit", "Add", "Read" ] ],
    }
addableTables["Company"]={
    "AccountId" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "Address1Type" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Address2Street1" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Address2Street2" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Address2Type" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Address3Street1" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Address3Street2" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Address3Type" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Anniversary" : ["Date", [ "Edit", "Delete", "Add", "Read" ] ],
    "AssistantName" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "AssistantPhone" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "BillingInformation" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Birthday" : ["Date", [ "Edit", "Delete", "Add", "Read" ] ],
    "City" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "City2" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "City3" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Company" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "CompanyID" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "ContactNotes" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "ContactType" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Country" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Country2" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Country3" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Email" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "EmailAddress2" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "EmailAddress3" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Fax1" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Fax1Type" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Fax2" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Fax2Type" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "FirstName" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "JobTitle" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "LastName" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "MiddleName" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Nickname" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "OwnerID" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "Password" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone1" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone1Ext" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone1Type" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone2" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone2Ext" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone2Type" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone3" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone3Ext" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone3Type" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone4" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone4Ext" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone4Type" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone5" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone5Ext" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone5Type" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "PostalCode" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "PostalCode2" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "PostalCode3" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "ReferralCode" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "SpouseName" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "State" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "State2" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "State3" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "StreetAddress1" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "StreetAddress2" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Suffix" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Title" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Username" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Website" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "ZipFour1" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "ZipFour2" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "ZipFour3" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    }
addableTables["Contact"]={
    "AccountId" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "Address1Type" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Address2Street1" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Address2Street2" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Address2Type" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Address3Street1" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Address3Street2" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Address3Type" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Anniversary" : ["Date", [ "Edit", "Delete", "Add", "Read" ] ],
    "AssistantName" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "AssistantPhone" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "BillingInformation" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Birthday" : ["Date", [ "Edit", "Delete", "Add", "Read" ] ],
    "City" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "City2" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "City3" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Company" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "CompanyID" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "ContactNotes" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "ContactType" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Country" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Country2" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Country3" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Email" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "EmailAddress2" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "EmailAddress3" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Fax1" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Fax1Type" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Fax2" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Fax2Type" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "FirstName" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "JobTitle" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "LastName" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "LeadSourceId" : ["Id", [ "Edit", "Add", "Read" ] ],
    "Leadsource" : ["String", [ "Edit", "Add", "Read" ] ],
    "MiddleName" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Nickname" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "OwnerID" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "Password" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone1" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone1Ext" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone1Type" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone2" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone2Ext" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone2Type" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone3" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone3Ext" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone3Type" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone4" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone4Ext" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone4Type" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone5" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone5Ext" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Phone5Type" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "PostalCode" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "PostalCode2" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "PostalCode3" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "ReferralCode" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "SpouseName" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "State" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "State2" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "State3" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "StreetAddress1" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "StreetAddress2" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Suffix" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Title" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Username" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Website" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "ZipFour1" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "ZipFour2" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "ZipFour3" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    }
addableTables["ContactAction"]={
    "Accepted" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    "ActionDate" : ["DateTime", [ "Edit", "Delete", "Add", "Read" ] ],
    "ActionDescription" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "ActionType" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "CompletionDate" : ["DateTime", [ "Edit", "Delete", "Add", "Read" ] ],
    "ContactId" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "CreatedBy" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "CreationDate" : ["DateTime", [ "Edit", "Delete", "Add", "Read" ] ],
    "CreationNotes" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "EndDate" : ["DateTime", [ "Edit", "Delete", "Add", "Read" ] ],
    "IsAppointment" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    "ObjectType" : ["Enum", [ "Edit", "Delete", "Add", "Read" ] ],
    "OpportunityId" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "PopupDate" : ["DateTime", [ "Edit", "Delete", "Add", "Read" ] ],
    "Priority" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    "UserID" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    }
addableTables["ContactGroup"]={
    "GroupCategoryId" : ["Id", [ "Edit", "Add", "Read" ] ],
    "GroupDescription" : ["String", [ "Edit", "Add", "Read" ] ],
    "GroupName" : ["String", [ "Edit", "Add", "Read" ] ],
    }
addableTables["ContactGroupCategory"]={
    "CategoryDescription" : ["String", [ "Edit", "Add", "Read" ] ],
    "CategoryName" : ["String", [ "Edit", "Add", "Read" ] ],
    }
addableTables["CreditCard"]={
    "BillAddress1" : ["String", [ "Edit", "Add", "Read" ] ],
    "BillAddress2" : ["String", [ "Edit", "Add", "Read" ] ],
    "BillCity" : ["String", [ "Edit", "Add", "Read" ] ],
    "BillCountry" : ["String", [ "Edit", "Add", "Read" ] ],
    "BillName" : ["String", [ "Edit", "Add", "Read" ] ],
    "BillState" : ["String", [ "Edit", "Add", "Read" ] ],
    "BillZip" : ["String", [ "Edit", "Add", "Read" ] ],
    "CVV2" : ["String", [ "Edit", "Add" ] ],
    "CardNumber" : ["String", [ "Add" ] ],
    "CardType" : ["String", [ "Edit", "Add", "Read" ] ],
    "ContactId" : ["Id", [ "Add", "Read" ] ],
    "Email" : ["String", [ "Edit", "Add", "Read" ] ],
    "ExpirationMonth" : ["String", [ "Edit", "Add", "Read" ] ],
    "ExpirationYear" : ["String", [ "Edit", "Add", "Read" ] ],
    "FirstName" : ["String", [ "Edit", "Add", "Read" ] ],
    "LastName" : ["String", [ "Edit", "Add", "Read" ] ],
    "MaestroIssueNumber" : ["String", [ "Edit", "Add", "Read" ] ],
    "NameOnCard" : ["String", [ "Edit", "Add", "Read" ] ],
    "PhoneNumber" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShipAddress1" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShipAddress2" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShipCity" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShipCompanyName" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShipCountry" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShipFirstName" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShipLastName" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShipMiddleName" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShipName" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShipPhoneNumber" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShipState" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShipZip" : ["String", [ "Edit", "Add", "Read" ] ],
    "StartDateMonth" : ["String", [ "Edit", "Add", "Read" ] ],
    "StartDateYear" : ["String", [ "Edit", "Add", "Read" ] ],
    }
addableTables["InvoiceItem"]={
    "CommissionStatus" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "Description" : ["String", [ "Edit", "Add", "Read" ] ],
    "Discount" : ["Double", [ "Edit", "Add", "Read" ] ],
    "InvoiceAmt" : ["Double", [ "Edit", "Add", "Read" ] ],
    "InvoiceId" : ["Id", [ "Edit", "Add", "Read" ] ],
    }
addableTables["Job"]={
    "ContactId" : ["Id", [ "Edit", "Add", "Read" ] ],
    "DueDate" : ["Date", [ "Edit", "Add", "Read" ] ],
    "JobNotes" : ["String", [ "Edit", "Add", "Read" ] ],
    "JobStatus" : ["String", [ "Edit", "Add", "Read" ] ],
    "JobTitle" : ["String", [ "Edit", "Add", "Read" ] ],
    "OrderStatus" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "OrderType" : ["String", [ "Edit", "Add", "Read" ] ],
    "ProductId" : ["Id", [ "Edit", "Add", "Read" ] ],
    "ShipCity" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShipCompany" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShipCountry" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShipFirstName" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShipLastName" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShipMiddleName" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShipPhone" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShipState" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShipStreet1" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShipStreet2" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShipZip" : ["String", [ "Edit", "Add", "Read" ] ],
    "StartDate" : ["Date", [ "Edit", "Add", "Read" ] ],
    }
addableTables["JobRecurringInstance"]={
    "AutoCharge" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "Description" : ["String", [ "Edit", "Add", "Read" ] ],
    "EndDate" : ["Date", [ "Edit", "Add", "Read" ] ],
    "InvoiceItemId" : ["Id", [ "Edit", "Add", "Read" ] ],
    "RecurringId" : ["Id", [ "Edit", "Add", "Read" ] ],
    "StartDate" : ["Date", [ "Edit", "Add", "Read" ] ],
    "Status" : ["Integer", [ "Edit", "Add", "Read" ] ],
    }
addableTables["Lead"]={
    "AffiliateId" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "ContactID" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "CreatedBy" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "EstimatedCloseDate" : ["DateTime", [ "Edit", "Delete", "Add", "Read" ] ],
    "LastUpdatedBy" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "Leadsource" : ["String", [ "Add", "Read" ] ],
    "NextActionDate" : ["DateTime", [ "Edit", "Delete", "Add", "Read" ] ],
    "NextActionNotes" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Objection" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "OpportunityNotes" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "OpportunityTitle" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "ProjectedRevenueHigh" : ["Double", [ "Edit", "Delete", "Add", "Read" ] ],
    "ProjectedRevenueLow" : ["Double", [ "Edit", "Delete", "Add", "Read" ] ],
    "StageID" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "StatusID" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "UserID" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    }
addableTables["LeadSource"]={
    "CostPerLead" : ["String", [ "Edit", "Add", "Read" ] ],
    "Description" : ["String", [ "Edit", "Add", "Read" ] ],
    "EndDate" : ["Date", [ "Edit", "Add", "Read" ] ],
    "LeadSourceCategoryId" : ["Id", [ "Edit", "Add", "Read" ] ],
    "Medium" : ["String", [ "Edit", "Add", "Read" ] ],
    "Message" : ["String", [ "Edit", "Add", "Read" ] ],
    "Name" : ["String", [ "Edit", "Add", "Read" ] ],
    "StartDate" : ["Date", [ "Edit", "Add", "Read" ] ],
    "Status" : ["String", [ "Edit", "Add", "Read" ] ],
    "Vendor" : ["String", [ "Edit", "Add", "Read" ] ],
    }
addableTables["LeadSourceCategory"]={
    "Description" : ["String", [ "Edit", "Add", "Read" ] ],
    "Name" : ["String", [ "Edit", "Add", "Read" ] ],
    }
addableTables["LeadSourceExpense"]={
    "Amount" : ["Double", [ "Edit", "Delete", "Add", "Read" ] ],
    "DateIncurred" : ["DateTime", [ "Edit", "Delete", "Add", "Read" ] ],
    "LeadSourceId" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "LeadSourceRecurringExpenseId" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "Notes" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Title" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    }
addableTables["LeadSourceRecurringExpense"]={
    "Amount" : ["Double", [ "Edit", "Delete", "Add", "Read" ] ],
    "EndDate" : ["DateTime", [ "Edit", "Delete", "Add", "Read" ] ],
    "LeadSourceId" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "NextExpenseDate" : ["DateTime", [ "Edit", "Delete", "Add", "Read" ] ],
    "Notes" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "StartDate" : ["DateTime", [ "Edit", "Delete", "Add", "Read" ] ],
    "Title" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    }
addableTables["OrderItem"]={
    "CPU" : ["Double", [ "Edit", "Add", "Read" ] ],
    "ItemDescription" : ["String", [ "Edit", "Add", "Read" ] ],
    "ItemName" : ["String", [ "Edit", "Add", "Read" ] ],
    "ItemType" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "Notes" : ["String", [ "Edit", "Add", "Read" ] ],
    "OrderId" : ["Id", [ "Edit", "Add", "Read" ] ],
    "PPU" : ["Double", [ "Edit", "Add", "Read" ] ],
    "ProductId" : ["Id", [ "Edit", "Add", "Read" ] ],
    "Qty" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "SubscriptionPlanId" : ["Id", [ "Edit", "Add", "Read" ] ],
    }
addableTables["Product"]={
    "BottomHTML" : ["String", [ "Edit", "Add", "Read" ] ],
    "CityTaxable" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "CountryTaxable" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "Description" : ["String", [ "Edit", "Add", "Read" ] ],
    "HideInStore" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "InventoryLimit" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "InventoryNotifiee" : ["String", [ "Edit", "Add", "Read" ] ],
    "IsPackage" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "LargeImage" : ["Blob", [ "Edit", "Add", "Read" ] ],
    "NeedsDigitalDelivery" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "ProductName" : ["String", [ "Edit", "Add", "Read" ] ],
    "ProductPrice" : ["Double", [ "Edit", "Add", "Read" ] ],
    "Shippable" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "ShippingTime" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShortDescription" : ["String", [ "Edit", "Add", "Read" ] ],
    "Sku" : ["String", [ "Edit", "Add", "Read" ] ],
    "StateTaxable" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "Status" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "Taxable" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "TopHTML" : ["String", [ "Edit", "Add", "Read" ] ],
    "Weight" : ["Double", [ "Edit", "Add", "Read" ] ],
    }
addableTables["ProductCategory"]={
    "CategoryDisplayName" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "CategoryImage" : ["Blob", [ "Edit", "Delete", "Add", "Read" ] ],
    "CategoryOrder" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    "ParentId" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    }
addableTables["ProductCategoryAssign"]={
    "ProductCategoryId" : ["Id", [ "Edit", "Add", "Read" ] ],
    "ProductId" : ["Id", [ "Edit", "Add", "Read" ] ],
    }
addableTables["ProductInterest"]={
    "DiscountPercent" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    "ObjType" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "ObjectId" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "ProductId" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "ProductType" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Qty" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    }
addableTables["ProductInterestBundle"]={
    "BundleName" : ["String", [ "Edit", "Add", "Read" ] ],
    "Description" : ["String", [ "Edit", "Add", "Read" ] ],
    }
addableTables["ProductOptValue"]={
    "Id" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "IsDefault" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    "Label" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Name" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "OptionIndex" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    "PriceAdjustment" : ["Double", [ "Edit", "Delete", "Add", "Read" ] ],
    "ProductOptionId" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "Sku" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    }
addableTables["ProductOption"]={
    "AllowSpaces" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    "CanContain" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "CanEndWith" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    "CanStartWith" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "Id" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "IsRequired" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    "Label" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "MaxChars" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    "MinChars" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    "Name" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "OptionType" : ["Enum", [ "Edit", "Delete", "Add", "Read" ] ],
    "Order" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    "ProductId" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "TextMessage" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    }
addableTables["RecurringOrder"]={
    "AffiliateId" : ["Id", [ "Edit", "Add", "Read" ] ],
    "AutoCharge" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "BillingAmt" : ["Double", [ "Edit", "Add", "Read" ] ],
    "BillingCycle" : ["String", [ "Edit", "Add", "Read" ] ],
    "CC1" : ["Id", [ "Edit", "Add", "Read" ] ],
    "CC2" : ["Id", [ "Edit", "Add", "Read" ] ],
    "ContactId" : ["Id", [ "Edit", "Add", "Read" ] ],
    "EndDate" : ["Date", [ "Edit", "Add", "Read" ] ],
    "Frequency" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "LastBillDate" : ["Date", [ "Edit", "Add", "Read" ] ],
    "LeadAffiliateId" : ["Id", [ "Edit", "Add", "Read" ] ],
    "MaxRetry" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "MerchantAccountId" : ["Id", [ "Edit", "Add", "Read" ] ],
    "NumDaysBetweenRetry" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "PaidThruDate" : ["Date", [ "Edit", "Add", "Read" ] ],
    "ProductId" : ["Id", [ "Edit", "Add", "Read" ] ],
    "ProgramId" : ["Id", [ "Edit", "Add", "Read" ] ],
    "PromoCode" : ["String", [ "Edit", "Add", "Read" ] ],
    "Qty" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "ReasonStopped" : ["String", [ "Edit", "Add", "Read" ] ],
    "ShippingOptionId" : ["Id", [ "Edit", "Add", "Read" ] ],
    "StartDate" : ["Date", [ "Edit", "Add", "Read" ] ],
    "Status" : ["String", [ "Edit", "Add", "Read" ] ],
    "SubscriptionPlanId" : ["Id", [ "Edit", "Add", "Read" ] ],
    }
addableTables["Referral"]={
    "AffiliateId" : ["Id", [ "Add", "Read" ] ],
    "ContactId" : ["Id", [ "Add", "Read" ] ],
    "DateExpires" : ["Date", [ "Add", "Read" ] ],
    "DateSet" : ["Date", [ "Add", "Read" ] ],
    "IPAddress" : ["String", [ "Add", "Read" ] ],
    "Info" : ["String", [ "Add", "Read" ] ],
    "Source" : ["String", [ "Add", "Read" ] ],
    "Type" : ["Integer", [ "Add", "Read" ] ],
    }
addableTables["SubscriptionPlan"]={
    "Active" : ["Boolean", [ "Edit", "Add", "Read" ] ],
    "Cycle" : ["String", [ "Edit", "Add", "Read" ] ],
    "Frequency" : ["Integer", [ "Edit", "Add", "Read" ] ],
    "PlanPrice" : ["Double", [ "Edit", "Add", "Read" ] ],
    "PreAuthorizeAmount" : ["Double", [ "Edit", "Add", "Read" ] ],
    "ProductId" : ["Id", [ "Edit", "Add", "Read" ] ],
    "Prorate" : ["Boolean", [ "Edit", "Add", "Read" ] ],
    }
addableTables["Ticket"]={
    "CloseDate" : ["Date", [ "Edit", "Delete", "Add", "Read" ] ],
    "ContactId" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "CreatedBy" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "DateInStage" : ["Date", [ "Edit", "Delete", "Add", "Read" ] ],
    "DevId" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "FolowUpDate" : ["Date", [ "Edit", "Delete", "Add", "Read" ] ],
    "HasCustomerCalled" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    "IssueId" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "LastUpdatedBy" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "Ordering" : ["Double", [ "Edit", "Delete", "Add", "Read" ] ],
    "Priority" : ["Integer", [ "Edit", "Delete", "Add", "Read" ] ],
    "Stage" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "Summary" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "TargetCompletionDate" : ["Date", [ "Edit", "Delete", "Add", "Read" ] ],
    "TicketApplication" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "TicketCategory" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "TicketTitle" : ["String", [ "Edit", "Delete", "Add", "Read" ] ],
    "TicketTypeId" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    "TimeSpent" : ["Double", [ "Edit", "Delete", "Add", "Read" ] ],
    "UserId" : ["Id", [ "Edit", "Delete", "Add", "Read" ] ],
    }